image:
  # credit to https://community.gitpod.io/t/downgrade-default-php-v7-4-3-to-7-1-3-or-7-2/3099/4?u=tkgc
  #   due to php 7.2 gives trouble to cakephp, now downgrade
  #   details:  https://github.com/cakephp/cakephp/issues/10862
  file: .gitpod.php7.1-Dockerfile
tasks:
  # not forget to --no-interaction  so prebuild will not stuck!
  - init: |
      composer install --no-interaction 
    # fix authentication "The server requested authentication method unknown to the client"
    #   thanks to https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to 
    command: |
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
      mysql -e "create database my_app"
      mysql -D my_app < config/schema/app.sql 
      mysql -D my_app < config/schema/i18n.sql 
      mysql -D my_app < config/schema/sessions.sql 
      bin/cake server
