image:
  # credit to https://community.gitpod.io/t/downgrade-default-php-v7-4-3-to-7-1-3-or-7-2/3099/4?u=tkgc
  file: .gitpod.php7.2-Dockerfile
tasks:
  - init: |
      composer install
    command: |
      echo 'TODO: start app'