image:
  # credit to https://community.gitpod.io/t/downgrade-default-php-v7-4-3-to-7-1-3-or-7-2/3099/4?u=tkgc
  file: .gitpod.php7.2-Dockerfile
tasks:
  - init: |
      composer install
    # fix authentication "The server requested authentication method unknown to the client"
    #   thanks to https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to 
    command: |
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
      bin/cake server
